import localFont from "next/font/local";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import Navbar from "@/components/Share/Navbar";
import Footer from "@/components/Share/Footer";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const roboto_init = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "700"],
  variable: "--font-roboto",
});
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "woof spot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden bg-[#FFFAF5]`}>
        {/* Fixed Navbar */}
        {/* <div className="sticky top-0  z-50 ">
          <Navbar />
        </div> */}
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
